### ISSUE TITLE
Run it in a subdomain

### ISSUE THREAD

**Issue by cybermarkus1** [tatsuyaoiw/twitter#21]
Hi! amazing work, i have been trying to run this app on my server under a subdomain through nginx
server: myserver.com
twitter node app: myserver.com/twitter

everything is broke. Do you know any efficient way to redirect every single route?

**Comment by cybermarkus1** [comment]
i was overriding locals, my fault.

Awesome work!

**Comment by tatsuyaoiw** [comment]
Good news! Thanks for letting me know.
